name: "📝 Mistake report"
description: "Report that something the contents of this repository contain some kind of mistake, unrelated to programming."
title: 'Mistake: '
labels: 
  - "mistake"
assignees: []

body:
  - type: input
    id: "description"
    attributes:
      label: "Describe the mistake"
      description: |-
        A clear and concise description of what the mistake is.
        Be sure to include the location of the mistake!
        If applicable, add screenshots to help explain your problem.
        You can paste screenshots here and GitHub will convert them to Markdown for you.
      placeholder: |-
        At page 123, it says that 1+1=3.
        That's wrong, it equals 2!

  - type: input
    id: "extra"
    attributes:
      label: "Additional information"
      description: >-
        Add any additional information about the mistake here.
      placeholder: >-
        ...
