name: "Build and release Docker image on ghcr.io"

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  buildrelease:
    name: "Build and release Docker image on ghcr.io"
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "linux/amd64"
            rusttarget: "x86_64-unknown-linux-gnu"
          - platform: "linux/arm/v7"
            rusttarget: "armv7-unknown-linux-gnueabihf"
          - platform: "linux/arm64/v8"
            rusttarget: "aarch64-unknown-linux-gnu"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Find the release semantic version"
        id: semver
        uses: Steffo99/actions-semver@v0.3.5
        with:
          string: ${{ github.ref_name }}

      - name: "Setup qemu"
        uses: docker/setup-qemu-action@v2
        if: ${{ matrix.arch }}
        with:
          platforms: ${{ matrix.arch }}

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ matrix.platform }}

      - name: "Login to GitHub Containers"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Find the lowercase name of the repository"
        id: reponame
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: "Build and push the Docker image"
        uses: docker/build-push-action@v3
        with:
          target: "final"
          platforms: ${{ matrix.platform }}
          build-args: >-
            RUSTTARGET=${{ matrix.rusttarget }}
          tags: >-
            ghcr.io/${{ steps.reponame.outputs.lowercase }}:${{ steps.semver.outputs.precedence }},
            ghcr.io/${{ steps.reponame.outputs.lowercase }}:${{ steps.semver.outputs.core }},
            ghcr.io/${{ steps.reponame.outputs.lowercase }}:${{ steps.semver.outputs.pair }},
            ghcr.io/${{ steps.reponame.outputs.lowercase }}:${{ steps.semver.outputs.major }},
            ghcr.io/${{ steps.reponame.outputs.lowercase }}:latest
          push: true
