name: "Release package on PyPI"

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  release:
    name: "Publish release on PyPI"
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
    
    steps:
      - name: "Download built packages from artifacts"
        uses: actions/download-artifact@v3
        with:
          name: "Build"
          path: dist/

      - name: "Upload package"
        uses: pypa/gh-action-pypi-publish@release/v1
