name: "Test using Poetry and pytest and PostgreSQL"

# Requires the following dependencies
# pytest = "^6.2.5"
# pytest-github-actions-annotate-failures = "^0.1.6"
# pytest-cov = "^3.0.0"

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: "Test using Poetry and pytest"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Setup Poetry"
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: "1.3.1"

      - name: "Setup Poetry Python environment"
        id: pyenv
        uses: Steffo99/actions-poetry-deps@v0.2.5

      - name: "Run tests"
        run: |
          source ${{ steps.pyenv.outputs.pyenv }}/activate
          pytest --verbose --cov=. --cov-report=html

      - name: "Upload coverage"
        uses: actions/upload-artifact@v3
        with:
          name: "Coverage"
          path: htmlcov
